apiVersion: batch/v1
kind: Job
metadata:
  name: api-database-load
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-database
        image: quay.io/eformat/curriki-database-load:latest
        command: ['sh', '-c', "until nslookup acid-postgresql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres-master service; sleep 3; done"]
