---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: pg-replica
    app.kubernetes.io/component: pg-replica
    app.kubernetes.io/instance: pg-replica
  name: postgresql-slave
spec:
  replicas: 3
