---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ include "curriki-ui.fullname" . }}:{{ .Values.image_version }}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"curriki-ui\")].image","pause":"false"}]'
  labels:
    {{- include "curriki-ui.labels" . | nindent 4 }}
  name: {{ include "curriki-ui.fullname" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
    {{- include "curriki-ui.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "curriki-ui.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: ' '
        imagePullPolicy: Always
        name: curriki-ui
        livenessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/certs/tls.crt
          name: tls-crt
          subPath: tls.crt
        - mountPath: /etc/nginx/certs/tls.key
          name: tls-key
          subPath: tls.key
        - mountPath: /etc/nginx/certs/ca.crt
          name: ca-crt
          subPath: ca.crt
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: curriki-ui
        name: curriki-ui-env
      - name: tls-crt
        secret:
          defaultMode: 420
          secretName: curriki-ui-tls
      - name: tls-key
        secret:
          defaultMode: 420
          secretName: curriki-ui-tls
      - name: ca-crt
        secret:
          defaultMode: 420
          secretName: curriki-ui-tls-ca
