---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    {{- include "curriki-ui.labels" . | nindent 4 }}
  name: {{ include "curriki-ui.fullname" . }}
  creationTimestamp: null
spec:
  lookupPolicy:
    local: false
{{- if (eq .Values.istag.enabled true) }}
  tags:
    - from:
        kind: DockerImage
        name: {{ .Values.image_repository }}/{{ .Values.image_namespace }}/{{ .Values.image_name }}:{{ .Values.image_version }}
      importPolicy: {}
      name: {{ .Chart.AppVersion }}
{{ end }}