apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    {{- include "curriki-ui.labels" . | nindent 4 }}
  name: {{ include "curriki-ui.fullname" . }}
spec:
  lookupPolicy:
    local: false
