---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    {{- include "curriki-admin.labels" . | nindent 4 }}
  name: {{ include "curriki-admin.fullname" . }}

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: aws-efs
  volumeMode: Filesystem