kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  labels:
    {{- include "curriki-admin.labels" . | nindent 4 }}
  name: {{ include "curriki-admin.fullname" . }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "curriki-admin.fullname" . }}:{{ .Values.image_version }}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.admin
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/imcoder001/curriki-docker'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: {{ include "curriki-admin.fullname" . }}-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: {{ include "curriki-admin.fullname" . }}-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial