apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: curriki-ui
    app.kubernetes.io/component: curriki-ui
    app.kubernetes.io/instance: curriki-ui
    app.kubernetes.io/part-of: curriki
  name: curriki-ui
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: curriki-ui
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
  labels:
    app: curriki-ui
    app.kubernetes.io/component: curriki-ui
    app.kubernetes.io/instance: curriki-ui
    app.kubernetes.io/part-of: curriki
  name: curriki-ui-api
spec:
  path: /api
  port:
    targetPort: 8000-tcp
  to:
    kind: Service
    name: curriki-api
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: curriki-ui
    app.kubernetes.io/component: curriki-ui
    app.kubernetes.io/instance: curriki-ui
    app.kubernetes.io/part-of: curriki
  name: curriki-ui-storage
spec:
  path: /storage
  port:
    targetPort: 8000-tcp
  to:
    kind: Service
    name: curriki-api
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: curriki-ui
    app.kubernetes.io/component: curriki-ui
    app.kubernetes.io/instance: curriki-ui
    app.kubernetes.io/part-of: curriki
  name: curriki-ui-socket
spec:
  path: /socket.io
  port:
    targetPort: 6001-tcp
  to:
    kind: Service
    name: curriki-api
    weight: 100
  wildcardPolicy: None