---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "curriki-tsugi.labels" . | nindent 4 }}
  name: {{ include "curriki-tsugi.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
