apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "curriki-tsugi.labels" . | nindent 4 }}
  name: {{ include "curriki-tsugi.fullname" . }}
spec:
  ports:
  - name: 9999-tcp
    port: 9999
    targetPort: 9999
  selector:
    {{- include "curriki-tsugi.selectorLabels" . | nindent 4 }}
