---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: redis-enterprise
    redis.io/cluster: rec
  name: rec-ui
spec:
  port:
    targetPort: ui
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: rec-ui
    weight: 100
  wildcardPolicy: None
