---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: openshift-monitoring-datasource
  namespace: openshift-user-workload-monitoring
spec:
  datasources:
  - access: proxy
    basicAuth: false
    editable: true
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      timeInterval: 5s
      tlsSkipVerify: true
    name: Prometheus-oauth
    secureJsonData:
      httpHeaderValue1: Bearer <fixme - bearer token from secret - how to mount this>
    type: prometheus
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    withCredentials: false
  name: openshift-metrics-datasources.yaml
