---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-user-workload-monitoring

resources:
- operatorgroup.yaml
- grafana-subscription.yaml
- grafana-cr.yaml
- grafana-fpm-dashboard.yaml
#- grafana-ds.yaml
