---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/yugabyte-operator.openshift-operators: ""
  name: yugabyte-operator
  namespace: openshift-operators
spec:
  channel: beta
  installPlanApproval: Automatic
  name: yugabyte-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: yugabyte-operator.v0.9.0