apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: curriki-postgresql
spec:
  teamId: "curriki"
  volume:
    size: 10Gi
  numberOfInstances: 3
  users:
    curriki:  # database owner
      - superuser
      - createdb
    curriki-replication: []  # role for application foo
  databases:
    currikidb: curriki  # dbname: owner
  # preparedDatabases:
  #   bar: {}
  postgresql:
    version: "12"
    parameters:  # Expert section
      shared_buffers: "512MB"
      max_connections: "500"
      log_statement: "all"
  resources:
    requests:
      cpu: '500m'
      memory: 1Gi
    limits:
      cpu: '2'
      memory: 7Gi
  patroni:
    synchronous_mode: true
    synchronous_mode_strict: true


