apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o openshift/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: tsugi-db
  name: tsugi-db
spec:
  ports:
  - name: "33306"
    port: 33306
    targetPort: 3306
  selector:
    io.kompose.service: tsugi-db
