apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o openshift/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: tsugi-web
  name: tsugi-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tsugi-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o openshift/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: tsugi-web
    spec:
      containers:
      - args:
        - bash
        - -c
        - ./tsugi/docker-compose-init.sh
        image: quay.io/curriki/tsugi-web
        imagePullPolicy: "Always"
        name: tsugi-web
        ports:
        - containerPort: 9999
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
