---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pg-replica
    app.kubernetes.io/component: pg-replica
    app.kubernetes.io/instance: pg-replica
    name: postgresql-master
  name: postgresql-master
spec:
  clusterIP: None
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgresql-master
  sessionAffinity: None
  type: ClusterIP
