{{- if (eq .Values.builds.enabled true) }}
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ include "curriki-api-base.fullname" . }}
  labels:
    {{- include "curriki-api.labels" . | nindent 4 }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "curriki-api-base.fullname" . }}:{{ .Values.image_version }}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.api.base
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.builds.git_url | quote }}
    contextDir: /
  triggers:
    - type: ConfigChange
  runPolicy: Serial
{{ end }}
