---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "curriki-api.fullname" . }}
  labels:
    {{- include "curriki-api.labels" . | nindent 4 }}
data:
  .env: |-
    APP_NAME=Curriki
    APP_ENV=local
    APP_KEY={{ .Values.api_key }}
    APP_DEBUG=true
    APP_URL=/api

    FRONT_END_URL=

    LOG_CHANNEL=stack

    DB_CONNECTION={{ .Values.db_connection }}
    DB_HOST={{ .Values.db_host }}
    DB_READ_HOST={{ .Values.db_read_host }}
    DB_WRITE_HOST={{ .Values.db_write_host }}
    DB_PORT={{ .Values.db_port }}
    DB_DATABASE={{ .Values.db_database }}
    DB_USERNAME={{ .Values.db_username }}
    DB_PASSWORD={{ .Values.db_password }}

    BROADCAST_DRIVER=redis
    CACHE_DRIVER=file
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    QUEUE_CONNECTION=database
    REDIS_HOST={{ .Values.redis_host }}
    REDIS_PASSWORD={{ .Values.redis_password | quote }}
    REDIS_PORT={{ .Values.redis_port }}
    REDIS_PREFIX=

    MAIL_MAILER=smtp
    MAIL_HOST={{ .Values.mail_host }}
    MAIL_PORT={{ .Values.mail_port }}
    MAIL_FROM_ADDRESS={{ .Values.mail_from_address }}
    MAIL_FROM_NAME="${APP_NAME}"

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_APP_CLUSTER=mt1

    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

    MATTERMOST_SERVER=default
    MATTERMOST_HOST=
    MATTERMOST_LOGIN=
    MATTERMOST_PASSWORD=
    MATTERMOST_DEFAULT_TEAM_ID=

    GAPI_CLASSROOM_CREDENTIALS=
    GAPI_CLIENT_ID=

    CURRIKI_TSUGI_HOST=

    ELASTIC_HOST={{ .Values.elastic_host }}
    ELASTIC_USER={{ .Values.elastic_user }}
    ELASTIC_PASS={{ .Values.elastic_pass | quote }}
    ELASTIC_MIGRATIONS_DIRECTORY=elastic/migrations
    SCOUT_DRIVER=elastic

    DEFAULT_THUMB_URL=

    CURRIKI_DEMO_EMAIL={{ .Values.curriki_demo_email }}
    XAPI_VERSION=1.0.3
    LRS_USERNAME=
    LRS_PASSWORD=
    LRS_REMOTE_URL=
    
