apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "curriki-api.fullname" . }}
  labels:
    {{- include "curriki-api.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      port: 8888-prom
      scheme: http
      path: /metrics
  selector:
    matchLabels:
    {{- include "curriki-api.selectorLabels" . | nindent 6 }}
