---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "curriki-api.fullname" . }}
  labels:
    {{- include "curriki-api.labels" . | nindent 4 }}
spec:
  ports:
    - name: 8000-tcp
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: 6001-tcp
      protocol: TCP
      port: 6001
      targetPort: 6001
  selector:
    {{- include "curriki-api.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
