apiVersion: batch/v1
kind: Job
metadata:
  name: api-es-index-load
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-database
        image: quay.io/fahad_curriki/curriki-es-index-load:latest
        command: ['sh', '-c', "until nslookup my-escluster-es-default.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for es service service; sleep 3; done"]
      containers:
      - name: load-es-index
        image: quay.io/masood_faisal/curriki-es-index-load:latest
        imagePullPolicy: Always
        command: [ "./load-index.sh" ]
      restartPolicy: Never
