---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: my-escluster
spec:
  auth: {}
  http:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - config:
      node.attr.attr_name: attr_value
      node.roles:
      - master
      - data
      node.store.allow_mmap: false
    count: 3
    name: default
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 2Gi
  version: 7.9.3
