---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: my-kibana
  name: my-kibana-kb-http
spec:
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: my-kibana-kb-http
    weight: 100
  wildcardPolicy: None
