kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: curriki-admin
  labels:
    app: curriki-admin
    app.kubernetes.io/component: curriki-admin
    app.kubernetes.io/instance: curriki-admin
    app.kubernetes.io/part-of: curriki
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'curriki-admin:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.admin
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/imcoder001/curriki-docker'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: curriki-admin-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: curriki-admin-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
