kind: ConfigMap
apiVersion: v1
metadata:
  name: curriki-api-echo-server
data:
  laravel-echo-server.json: |-
    {
      "authHost": "http://127.0.0.1:8000",
      "authEndpoint": "/api/broadcasting/auth",
      "clients": [],
      "database": "redis",
      "databaseConfig": {
        "redis": {
          "port": "17716",
          "host": "currikidb-headless.dev-redis.svc.cluster.local",
          "password": "HJCYWYhQ"
        },
        "sqlite": {
          "databasePath": "/database/laravel-echo-server.sqlite"
        }
      },
      "devMode": true,
      "host": null,
      "port": "6001",
      "protocol": "http",
      "socketio": {},
      "secureOptions": 67108864,
      "sslCertPath": "",
      "sslKeyPath": "",
      "sslCertChainPath": "",
      "sslPassphrase": "",
      "subscribers": {
        "http": true,
        "redis": true
      },
      "apiOriginAllow": {
        "allowCors": false,
        "allowOrigin": "",
        "allowMethods": "",
        "allowHeaders": ""
      }
    }

    
