kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: h5p-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: aws-efs
  volumeMode: Filesystem
