kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: curriki-api
  labels:
    app: curriki-api
    app.kubernetes.io/component: curriki-api
    app.kubernetes.io/instance: curriki-api
    app.kubernetes.io/part-of: curriki
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: curriki-api-base
  labels:
    app: curriki-api
    app.kubernetes.io/component: curriki-api
    app.kubernetes.io/instance: curriki-api
    app.kubernetes.io/part-of: curriki
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: curriki-api-fpm
  labels:
    app: curriki-api
    app.kubernetes.io/component: curriki-api
    app.kubernetes.io/instance: curriki-api
    app.kubernetes.io/part-of: curriki
spec:
  lookupPolicy:
    local: false
