kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: curriki-api
  labels:
    app: curriki-api
    app.kubernetes.io/component: curriki-api
    app.kubernetes.io/instance: curriki-api
    app.kubernetes.io/part-of: curriki
spec:
  to:
    kind: Service
    name: curriki-api
    weight: 100
  port:
    targetPort: 8000-tcp
  wildcardPolicy: None
