---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: admin-storage
  labels:
    {{- include "curriki-admin.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: aws-efs
  volumeMode: Filesystem
