---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: admin-storage
  labels:
    app: curriki-admin

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: aws-efs
  volumeMode: Filesystem
