{{- if (eq .Values.builds.enabled true) }}
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ include "curriki-admin.fullname" . }}
  labels:
    {{- include "curriki-admin.labels" . | nindent 4 }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: '{{.Values.image_name}}:{{.Values.image_version}}'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.admin
  postCommit: {}
  source:
    type: Git
    git:
      uri: '{{.Values.builds.git_url}}'
    contextDir: /
  triggers:
  - type: ConfigChange
  runPolicy: Serial
{{ end }}