---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ include "curriki-admin.fullname" . }}
  labels:
    {{- include "curriki-admin.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
{{- if (eq .Values.istag.enabled true) }}
  tags:
    - from:
        kind: DockerImage
        name: {{ .Values.image_repository }}/{{ .Values.image_namespace }}/{{ .Values.image_name }}:{{ .Values.image_version }}
      importPolicy: {}
      name: {{ .Chart.AppVersion }}
{{ end }}