---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "curriki-admin.fullname" . }}
  labels:
    {{- include "curriki-admin.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "curriki-admin.fullname" . }}
    weight: 100
  port:
    targetPort: 6000-tcp
  wildcardPolicy: None
