kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: curriki-admin
  labels:
    app: curriki-admin
    app.kubernetes.io/component: curriki-admin
    app.kubernetes.io/instance: curriki-admin
    app.kubernetes.io/part-of: curriki
spec:
  to:
    kind: Service
    name: curriki-admin
    weight: 100
  port:
    targetPort: 6000-tcp
  wildcardPolicy: None
