kind: Service
apiVersion: v1
metadata:
  name: curriki-admin
  labels:
    app: curriki-admin
    app.kubernetes.io/component: curriki-admin
    app.kubernetes.io/instance: curriki-admin
    app.kubernetes.io/part-of: curriki
spec:
  ports:
    - name: 6000-tcp
      protocol: TCP
      port: 6000
      targetPort: 6000
  selector:
    app: curriki-admin
    deploymentconfig: curriki-admin
  type: ClusterIP
  sessionAffinity: None