---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "curriki-admin.fullname" . }}
  labels:
    {{- include "curriki-admin.labels" . | nindent 4 }}
spec:
  ports:
    - name: 6000-tcp
      protocol: TCP
      port: 6000
      targetPort: 6000
  selector:
    {{- include "curriki-admin.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None