---
apiVersion: v1
data:
  database-name: c2FtcGxlZGI=
  database-password: cGFzc3dvcmQ=
  database-root-password: cGFzc3dvcmQ=
  database-user: dXNlcg==
kind: Secret
metadata:
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: mysql
  name: mysql
type: Opaque
